name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v1

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Validate Prerequisite Packer template
      run: packer validate ./prerequisite.json.pkr.hcl

    - name: Build Prerequisite Packer template
      run: packer build ./prerequisite.json.pkr.hcl
      
    - name: Validate Application Packer template
      run: packer validate ./application.json.pkr.hcl

    - name: Build Application Packer template
      run: packer build -var "source_ami=ami-0a577f9ef132cbd42" ./application.json.pkr.hcl
